package com.cashproject.mongsil.kmp.core.datastore

const val SETTINGS_PREFERENCES_NAME = "SETTINGS_PREFERENCES.preferences_pb"
const val KEY_IS_DARK_THEME = "IS_DARK_THEME"
const val KEY_THEME_MODE = "THEME_MODE"
const val KEY_FONT_STYLE_OPTION = "FONT_STYLE_OPTION"
const val KEY_FONT_SCALE = "FONT_SCALE"
const val KEY_IS_DIARY_REMINDER_ENABLED = "IS_DIARY_REMINDER_ENABLED"
const val KEY_IS_SCREEN_LOCK_ENABLED = "IS_SCREEN_LOCK_ENABLED"
const val KEY_SCREEN_LOCK_METHOD = "SCREEN_LOCK_METHOD"
const val KEY_SCREEN_LOCK_PASSWORD_HASH = "SCREEN_LOCK_PASSWORD_HASH"
